### ISSUE TITLE
Error al habilitar Purge v1.0.1 en la versión 1.19.4

### ISSUE THREAD

**Issue by AyanPR** [josantonius/minecraft-purge#1]
Instalé la versión 1.0.1 del plugin Purge en un servidor de Minecraft con la versión 1.19.4.
Al habilitar el plugin, se produjo el siguiente error:

**[Server thread/ERROR]**: Error occurred while enabling Purge v1.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/josantonius/minecraft/messaging/Message
at dev.josantonius.minecraft.purge.Main.load(Main.kt:267) ~[?:?]
at dev.josantonius.minecraft.purge.Main.onEnable(Main.kt:43) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.josantonius.minecraft.messaging.Message
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
... 13 more

**Comment by josantonius** [comment]
El plugin y la [biblioteca](https://github.com/josantonius/minecraft-messaging) que te da error fueron desarrollados para la versión 1.19.3 (se indica en la documentación).

Lo desarrollé por encargo para un evento en concreto y por ahora no tengo previsto hacerlo compatible con versiones más recientes.
